In [11]:
import pandas as pd
import requests
import json
import numpy as np
from datosgobmx import client 
import mplleaflet
import folium

%load_ext autoreload
%autoreload 2
%matplotlib inline

parametros_request = client.makeCall('sinaica-parametros')

valid_params = []

for v in parametros_request['results']:
    aux = pd.DataFrame.from_dict(v,orient = 'index').T
    valid_params.append(aux)
    
valid_params = pd.concat(valid_params, ignore_index= True)
valid_params['date-insert'] = pd.to_datetime(valid_params['date-insert'])
valid_params

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

                        _id parametro                      date-insert
0  5c2aa3dfe2705c1932134299        CO 2018-12-31 23:18:55.923000+00:00
1  5c2aa3dfe2705c193213429a        O3 2018-12-31 23:18:55.923000+00:00
2  5c2aa3dfe2705c193213429b      PM10 2018-12-31 23:18:55.923000+00:00
3  5c2aa3dfe2705c193213429c       SO2 2018-12-31 23:18:55.923000+00:00
4  5c2aa3dfe2705c193213429d       NO2 2018-12-31 23:18:55.923000+00:00
5  5c2aa3dfe2705c193213429e     PM2.5 2018-12-31 23:18:55.923000+00:00
6  5c2aa3dfe2705c193213429f       TMP 2018-12-31 23:18:55.923000+00:00

In [2]:
client.makeCall('sinaica', {'pageSize':5000})

{'pagination': {'pageSize': 5000, 'page': 1, 'total': 5051793},
 'results': [{'_id': '5ccceac5e2705c193233f569',
   'date': '2018-01-01T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.3865,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010101',
   'hora': 1,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56a',
   'date': '2018-01-01T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.8923,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010102',
   'hora': 2,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56b',
   'date': '2018-01-01T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.8105,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010103',
   'hora': 3,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56c',
   'date': '2018-01-01T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.4355,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010104',
   'hora': 4,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56d',
   'date': '2018-01-01T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.9326,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010105',
   'hora': 5,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56e',
   'date': '2018-01-01T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.8677,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010106',
   'hora': 6,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f56f',
   'date': '2018-01-01T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.9507,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010107',
   'hora': 7,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f570',
   'date': '2018-01-01T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.2974,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010108',
   'hora': 8,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f571',
   'date': '2018-01-01T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.6891,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010109',
   'hora': 9,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f572',
   'date': '2018-01-01T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.0474,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010110',
   'hora': 10,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f573',
   'date': '2018-01-01T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.71526,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010111',
   'hora': 11,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f574',
   'date': '2018-01-01T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.55633,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010112',
   'hora': 12,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f575',
   'date': '2018-01-01T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.54382,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010113',
   'hora': 13,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f576',
   'date': '2018-01-01T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.55089,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010114',
   'hora': 14,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f577',
   'date': '2018-01-01T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.58439,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010115',
   'hora': 15,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f578',
   'date': '2018-01-01T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.61626,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010116',
   'hora': 16,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f579',
   'date': '2018-01-01T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.59049,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010117',
   'hora': 17,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57a',
   'date': '2018-01-01T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.69288,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010118',
   'hora': 18,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57b',
   'date': '2018-01-01T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.5533,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010119',
   'hora': 19,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57c',
   'date': '2018-01-01T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.0583,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010120',
   'hora': 20,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57d',
   'date': '2018-01-01T21:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.9055,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010121',
   'hora': 21,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57e',
   'date': '2018-01-01T22:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.6002,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010122',
   'hora': 22,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f57f',
   'date': '2018-01-01T23:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.7369,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010123',
   'hora': 23,
   'fecha': '2018-01-01'},
  {'_id': '5ccceac5e2705c193233f580',
   'date': '2018-01-02T00:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.3251,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010200',
   'hora': 0,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f581',
   'date': '2018-01-02T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.3489,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010201',
   'hora': 1,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f582',
   'date': '2018-01-02T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.5158,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010202',
   'hora': 2,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f583',
   'date': '2018-01-02T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.4304,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010203',
   'hora': 3,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f584',
   'date': '2018-01-02T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.4315,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010204',
   'hora': 4,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f585',
   'date': '2018-01-02T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.4919,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010205',
   'hora': 5,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f586',
   'date': '2018-01-02T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.7193,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010206',
   'hora': 6,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f587',
   'date': '2018-01-02T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.1188,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010207',
   'hora': 7,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f588',
   'date': '2018-01-02T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.5056,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010208',
   'hora': 8,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f589',
   'date': '2018-01-02T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.3159,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010209',
   'hora': 9,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58a',
   'date': '2018-01-02T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.93638,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010210',
   'hora': 10,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58b',
   'date': '2018-01-02T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.83932,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010211',
   'hora': 11,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58c',
   'date': '2018-01-02T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.72842,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010212',
   'hora': 12,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58d',
   'date': '2018-01-02T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.77392,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010213',
   'hora': 13,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58e',
   'date': '2018-01-02T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.77824,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010214',
   'hora': 14,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f58f',
   'date': '2018-01-02T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.73088,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010215',
   'hora': 15,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f590',
   'date': '2018-01-02T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.75198,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010216',
   'hora': 16,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f591',
   'date': '2018-01-02T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.76346,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010217',
   'hora': 17,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f592',
   'date': '2018-01-02T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.86681,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010218',
   'hora': 18,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f593',
   'date': '2018-01-02T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.9509,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010219',
   'hora': 19,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f594',
   'date': '2018-01-02T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.6858,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010220',
   'hora': 20,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f595',
   'date': '2018-01-02T21:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.2525,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010221',
   'hora': 21,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f596',
   'date': '2018-01-02T22:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.0773,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010222',
   'hora': 22,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f597',
   'date': '2018-01-02T23:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.7502,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010223',
   'hora': 23,
   'fecha': '2018-01-02'},
  {'_id': '5ccceac5e2705c193233f598',
   'date': '2018-01-03T00:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.1973,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010300',
   'hora': 0,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f599',
   'date': '2018-01-03T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.89746,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010301',
   'hora': 1,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59a',
   'date': '2018-01-03T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.87701,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010302',
   'hora': 2,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59b',
   'date': '2018-01-03T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.76006,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010303',
   'hora': 3,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59c',
   'date': '2018-01-03T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.70318,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010304',
   'hora': 4,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59d',
   'date': '2018-01-03T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.66415,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010305',
   'hora': 5,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59e',
   'date': '2018-01-03T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.2258,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010306',
   'hora': 6,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f59f',
   'date': '2018-01-03T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.6283,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010307',
   'hora': 7,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a0',
   'date': '2018-01-03T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.0295,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010308',
   'hora': 8,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a1',
   'date': '2018-01-03T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.4369,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010309',
   'hora': 9,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a2',
   'date': '2018-01-03T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.148,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010310',
   'hora': 10,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a3',
   'date': '2018-01-03T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 1.0386,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010311',
   'hora': 11,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a4',
   'date': '2018-01-03T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.78343,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010312',
   'hora': 12,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a5',
   'date': '2018-01-03T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.62067,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010313',
   'hora': 13,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a6',
   'date': '2018-01-03T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.58582,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010314',
   'hora': 14,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a7',
   'date': '2018-01-03T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.65802,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010315',
   'hora': 15,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a8',
   'date': '2018-01-03T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.6283,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010316',
   'hora': 16,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5a9',
   'date': '2018-01-03T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.75388,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010317',
   'hora': 17,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5aa',
   'date': '2018-01-03T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 0.9898,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010318',
   'hora': 18,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5ab',
   'date': '2018-01-03T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.3806,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010319',
   'hora': 19,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5ac',
   'date': '2018-01-03T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.3849,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010320',
   'hora': 20,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5ad',
   'date': '2018-01-03T21:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.2387,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010321',
   'hora': 21,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5ae',
   'date': '2018-01-03T22:00:00.000Z',
   'validoorig': 1,
   'city': 'Guadalajara',
   'state': 'Jalisco',
   'valororig': 2.4634,
   'parametro': 'CO',
   'estacionesid': 101,
   'id': '101CO18010322',
   'hora': 22,
   'fecha': '2018-01-03'},
  {'_id': '5ccceac5e2705c193233f5af',

In [3]:
client.makeCall('sinaica', {'pageSize':5000, 'parametro':'O3', 'estacionesid':259, 'page':1})

{'pagination': {'pageSize': 5000, 'page': 1, 'total': 6793},
 'results': [{'_id': '5cccec08e2705c1932594247',
   'date': '2018-01-01T00:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.017,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010100',
   'hora': 0,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594248',
   'date': '2018-01-01T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.019,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010101',
   'hora': 1,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594249',
   'date': '2018-01-01T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.023,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010102',
   'hora': 2,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424a',
   'date': '2018-01-01T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.027,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010103',
   'hora': 3,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424b',
   'date': '2018-01-01T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.03,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010104',
   'hora': 4,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424c',
   'date': '2018-01-01T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.022,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010105',
   'hora': 5,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424d',
   'date': '2018-01-01T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.018,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010106',
   'hora': 6,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424e',
   'date': '2018-01-01T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.013,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010107',
   'hora': 7,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259424f',
   'date': '2018-01-01T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.006,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010108',
   'hora': 8,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594250',
   'date': '2018-01-01T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.012,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010109',
   'hora': 9,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594251',
   'date': '2018-01-01T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.022,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010110',
   'hora': 10,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594252',
   'date': '2018-01-01T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.033,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010111',
   'hora': 11,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594253',
   'date': '2018-01-01T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.048,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010112',
   'hora': 12,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594254',
   'date': '2018-01-01T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.061,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010113',
   'hora': 13,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594255',
   'date': '2018-01-01T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.071,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010114',
   'hora': 14,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594256',
   'date': '2018-01-01T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.082,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010115',
   'hora': 15,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594257',
   'date': '2018-01-01T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.085,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010116',
   'hora': 16,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594258',
   'date': '2018-01-01T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.084,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010117',
   'hora': 17,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c1932594259',
   'date': '2018-01-01T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.063,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010118',
   'hora': 18,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259425a',
   'date': '2018-01-01T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.032,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010119',
   'hora': 19,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259425b',
   'date': '2018-01-01T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.02,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010120',
   'hora': 20,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259425c',
   'date': '2018-01-01T21:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.015,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010121',
   'hora': 21,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259425d',
   'date': '2018-01-01T22:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.014,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010122',
   'hora': 22,
   'fecha': '2018-01-01'},
  {'_id': '5cccec08e2705c193259425e',
   'date': '2018-01-02T00:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.012,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010200',
   'hora': 0,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259425f',
   'date': '2018-01-02T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.013,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010201',
   'hora': 1,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594260',
   'date': '2018-01-02T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.008,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010202',
   'hora': 2,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594261',
   'date': '2018-01-02T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.004,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010203',
   'hora': 3,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594262',
   'date': '2018-01-02T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.005,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010204',
   'hora': 4,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594263',
   'date': '2018-01-02T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.006,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010205',
   'hora': 5,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594264',
   'date': '2018-01-02T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.002,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010206',
   'hora': 6,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594265',
   'date': '2018-01-02T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.001,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010207',
   'hora': 7,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594266',
   'date': '2018-01-02T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.001,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010208',
   'hora': 8,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594267',
   'date': '2018-01-02T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.005,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010209',
   'hora': 9,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594268',
   'date': '2018-01-02T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.014,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010210',
   'hora': 10,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594269',
   'date': '2018-01-02T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.02,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010211',
   'hora': 11,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426a',
   'date': '2018-01-02T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.034,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010212',
   'hora': 12,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426b',
   'date': '2018-01-02T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.052,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010213',
   'hora': 13,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426c',
   'date': '2018-01-02T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.066,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010214',
   'hora': 14,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426d',
   'date': '2018-01-02T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.07,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010215',
   'hora': 15,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426e',
   'date': '2018-01-02T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.074,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010216',
   'hora': 16,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c193259426f',
   'date': '2018-01-02T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.073,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010217',
   'hora': 17,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594270',
   'date': '2018-01-02T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.063,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010218',
   'hora': 18,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594271',
   'date': '2018-01-02T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.047,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010219',
   'hora': 19,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594272',
   'date': '2018-01-02T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.045,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010220',
   'hora': 20,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594273',
   'date': '2018-01-02T21:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.036,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010221',
   'hora': 21,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594274',
   'date': '2018-01-02T22:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.035,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010222',
   'hora': 22,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594275',
   'date': '2018-01-02T23:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.028,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010223',
   'hora': 23,
   'fecha': '2018-01-02'},
  {'_id': '5cccec08e2705c1932594276',
   'date': '2018-01-03T00:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.019,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010300',
   'hora': 0,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594277',
   'date': '2018-01-03T01:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.018,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010301',
   'hora': 1,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594278',
   'date': '2018-01-03T02:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.023,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010302',
   'hora': 2,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259427c',
   'date': '2018-01-03T03:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.022,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010303',
   'hora': 3,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259427d',
   'date': '2018-01-03T04:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.024,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010304',
   'hora': 4,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259427e',
   'date': '2018-01-03T05:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.018,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010305',
   'hora': 5,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259427f',
   'date': '2018-01-03T06:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.018,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010306',
   'hora': 6,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594280',
   'date': '2018-01-03T07:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.012,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010307',
   'hora': 7,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594281',
   'date': '2018-01-03T08:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.005,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010308',
   'hora': 8,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594282',
   'date': '2018-01-03T09:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.006,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010309',
   'hora': 9,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594283',
   'date': '2018-01-03T10:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.015,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010310',
   'hora': 10,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594284',
   'date': '2018-01-03T11:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.031,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010311',
   'hora': 11,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594285',
   'date': '2018-01-03T12:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.054,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010312',
   'hora': 12,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594286',
   'date': '2018-01-03T13:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.055,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010313',
   'hora': 13,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594287',
   'date': '2018-01-03T14:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.064,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010314',
   'hora': 14,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594288',
   'date': '2018-01-03T15:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.071,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010315',
   'hora': 15,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c1932594289',
   'date': '2018-01-03T16:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.077,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010316',
   'hora': 16,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259428a',
   'date': '2018-01-03T17:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.076,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010317',
   'hora': 17,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259428b',
   'date': '2018-01-03T18:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.051,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010318',
   'hora': 18,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259428c',
   'date': '2018-01-03T19:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',
   'state': 'Ciudad de México',
   'valororig': 0.037,
   'parametro': 'O3',
   'estacionesid': 259,
   'id': '259O318010319',
   'hora': 19,
   'fecha': '2018-01-03'},
  {'_id': '5cccec08e2705c193259428d',
   'date': '2018-01-03T20:00:00.000Z',
   'validoorig': 1,
   'city': 'Valle de México',

In [12]:
estaciones_request = client.makeCall('sinaica-estaciones', {'pageSize':200})

estaciones = []

for v in estaciones_request['results']:
    aux = pd.DataFrame.from_dict(v, orient='index').T
    estaciones.append(aux)
    
estaciones = pd.concat(estaciones, ignore_index=True)
estaciones['date-insert'] = pd.to_datetime(estaciones['date-insert'])
estaciones = estaciones.apply(lambda x: pd.to_numeric(x, errors='ignore') if x.name!='date-insert' else x)

print(estaciones.shape)
estaciones.head()

KeyError: 'date-insert'

In [9]:
estaciones.describe()

,_id,lat,long,id,nombre,codigo,redesid
count,185,185.0,185.0,185,185,185,185
unique,185,180.0,179.0,185,171,156,72
top,5cccf5bee2705c1932820610,0.0,0.0,428,Tecnológico,TEC,119
freq,1,4.0,4.0,1,3,9,40

In [10]:
estaciones.id.nunique(), estaciones._id.nunique(), estaciones.lat.nunique(), estaciones.long.nunique()

(185, 185, 180, 179)

In [14]:
# Estaciones son los datos obtenidos de la API, en formato Pandas DataFrame
# Hay estaciones con valores erróneos
estaciones.plot.scatter('long', 'lat', figsize=(8, 8))
mplleaflet.display()

/home/enrique/anaconda3/lib/python3.7/site-packages/IPython/core/display.py:717: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

In [15]:
# Estaciones son los datos obtenidos de la API, en formato Pandas DataFrame
# Hay estaciones con valores erróneos
centro_lat, centro_lon = 22.396092, -101.731430
folium_map = folium.Map(location=[centro_lat, centro_lon], zoom_start=5, tiles='cartodb positron')

for i, row in estaciones.iterrows():
    
    # generate the popup message that is shown on click.
    popup_text = f"<b> Nombre: </b> {row.nombre} <br> <b> Latitud: </b> {row.lat:.5f} <br> <b> Longitud: </b> {row.long:.5f} <br>"
    folium.CircleMarker(location=[row.lat, row.long], radius=5, tooltip=popup_text, fill=True,
                        fill_opacity=0.4).add_to(folium_map)
    
folium_map.save('../estaciones_todas.html')

folium_map

PermissionError: [Errno 13] Permission denied: '../estaciones_todas.html'

In [ ]:
# Guardamos lo datos para utilizarlos más adelante
estaciones.to_csv('/data_estaciones_sinaica.csv', index=False)