In [8]:
import pandas as pd

In [38]:
df = pd.read_csv('datos_abiertos_covid19.csv', nrows = 1000)

In [39]:
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [40]:
df.tail()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
995,2020-07-30,051cf3,2,4,9,1,9,9,5,1,...,2,1,2,2,99,1,99,México,99,97
996,2020-07-30,15afc2,2,4,21,2,21,21,114,1,...,2,2,2,2,99,1,99,México,99,97
997,2020-07-30,0734ea,2,4,15,1,15,15,121,1,...,2,1,2,2,99,1,99,México,99,97
998,2020-07-30,103b61,2,4,15,1,9,15,25,1,...,2,1,2,2,99,1,99,México,99,97
999,2020-07-30,0a1951,2,4,23,2,23,23,5,2,...,2,2,2,2,99,1,99,México,99,2

In [41]:
df.sample(frac = 1)

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
379,2020-07-30,08bb21,2,4,9,2,9,9,15,2,...,2,1,2,2,99,1,99,México,99,2
291,2020-07-30,0da6d6,2,4,31,2,31,31,101,1,...,2,2,2,2,99,1,99,México,99,97
491,2020-07-30,0c3ebb,2,3,2,1,2,2,2,1,...,2,2,2,2,1,1,99,México,99,97
386,2020-07-30,0a3d4d,2,3,2,2,25,2,2,1,...,2,1,2,2,1,1,99,México,99,97
865,2020-07-30,0aa443,2,4,9,2,9,9,17,1,...,2,1,2,2,99,1,99,México,99,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,2020-07-30,14b727,2,4,30,2,30,30,193,1,...,2,2,2,2,99,1,99,México,99,97
953,2020-07-30,1e2fbd,2,3,15,2,9,9,15,1,...,2,1,2,2,2,1,99,México,99,97
767,2020-07-30,0ab790,2,4,14,1,14,14,67,1,...,2,2,2,2,99,1,99,México,99,97
248,2020-07-30,171d4d,2,4,9,2,9,9,7,1,...,1,2,2,2,99,1,99,México,99,97
893,2020-07-30,0366b7,2,4,15,2,15,15,39,2,...,2,2,2,2,99,1,99,México,99,2

In [42]:
df.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [43]:
df.dtypes

FECHA_ACTUALIZACION    object
ID_REGISTRO            object
ORIGEN                  int64
SECTOR                  int64
ENTIDAD_UM              int64
SEXO                    int64
ENTIDAD_NAC             int64
ENTIDAD_RES             int64
MUNICIPIO_RES           int64
TIPO_PACIENTE           int64
FECHA_INGRESO          object
FECHA_SINTOMAS         object
FECHA_DEF              object
INTUBADO                int64
NEUMONIA                int64
EDAD                    int64
NACIONALIDAD            int64
EMBARAZO                int64
HABLA_LENGUA_INDIG      int64
DIABETES                int64
EPOC                    int64
ASMA                    int64
INMUSUPR                int64
HIPERTENSION            int64
OTRA_COM                int64
CARDIOVASCULAR          int64
OBESIDAD                int64
RENAL_CRONICA           int64
TABAQUISMO              int64
OTRO_CASO               int64
RESULTADO               int64
MIGRANTE                int64
PAIS_NACIONALIDAD      object
PAIS_ORIGEN             int64
UCI                     int64
dtype: object

In [44]:
df.values

array([['2020-07-30', '004228', 2, ..., 'México', 99, 97],
       ['2020-07-30', '1e6804', 2, ..., 'México', 99, 97],
       ['2020-07-30', '105b61', 2, ..., 'México', 99, 97],
       ...,
       ['2020-07-30', '0734ea', 2, ..., 'México', 99, 97],
       ['2020-07-30', '103b61', 2, ..., 'México', 99, 97],
       ['2020-07-30', '0a1951', 2, ..., 'México', 99, 2]], dtype=object)

In [45]:
df2 = df.head(10)

In [46]:
df2.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [47]:
df['SEXO'].head()

0    2
1    1
2    2
3    2
4    2
Name: SEXO, dtype: int64

In [48]:
df[100:110]

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
100,2020-07-30,052ffa,2,3,27,2,27,27,4,1,...,2,2,2,2,1,1,99,México,99,97
101,2020-07-30,118c61,2,3,27,1,27,27,13,1,...,2,2,2,2,1,1,99,México,99,97
102,2020-07-30,173741,2,4,2,2,12,2,4,2,...,2,2,2,2,99,1,99,México,99,2
103,2020-07-30,18542d,2,4,9,1,9,15,70,1,...,2,1,2,2,99,1,99,México,99,97
104,2020-07-30,1ab178,2,4,15,1,15,15,60,1,...,2,1,2,2,99,1,99,México,99,97
105,2020-07-30,052971,2,4,9,2,15,15,35,1,...,2,2,2,2,99,1,99,México,99,97
106,2020-07-30,108487,2,4,30,1,30,30,193,1,...,2,2,2,2,99,1,99,México,99,97
107,2020-07-30,18e5eb,2,3,25,2,25,25,6,1,...,2,2,2,2,1,1,99,México,99,97
108,2020-07-30,031691,2,4,9,2,9,15,33,1,...,2,2,2,2,99,1,99,México,99,97
109,2020-07-30,19d77e,2,4,15,1,15,9,6,1,...,2,2,2,2,99,1,99,México,99,97

In [54]:
df[df['OBESIDAD'] == 1].head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
10,2020-07-30,04be48,2,4,23,2,27,23,5,1,...,2,1,2,2,99,1,99,México,99,97
14,2020-07-30,198f2a,2,4,9,2,9,15,120,1,...,2,1,2,2,99,1,99,México,99,97
20,2020-07-30,17a849,2,4,1,2,16,1,1,1,...,2,1,2,2,99,1,99,México,99,97

In [56]:
df[df['PAIS_NACIONALIDAD']=='México'].head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [58]:
df[(df['PAIS_NACIONALIDAD']=='México') & (df['ENTIDAD_NAC'] != 25)].head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
5,2020-07-30,1aae75,2,3,15,1,15,15,106,1,...,2,2,2,2,1,1,99,México,99,97
6,2020-07-30,0fb250,2,4,30,2,30,30,193,2,...,2,2,1,2,99,1,99,México,99,2

In [59]:
df[df.ENTIDAD_NAC.isin(['27','2'])].head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
10,2020-07-30,04be48,2,4,23,2,27,23,5,1,...,2,1,2,2,99,1,99,México,99,97
16,2020-07-30,195210,2,3,2,2,2,2,2,1,...,2,2,2,2,1,1,99,México,99,97
17,2020-07-30,1dfaa5,2,3,27,2,27,27,4,1,...,2,2,2,2,1,1,99,México,99,97

In [60]:
df[pd.isna(df['PAIS_ORIGEN'])].head()

Empty DataFrame
Columns: [FECHA_ACTUALIZACION, ID_REGISTRO, ORIGEN, SECTOR, ENTIDAD_UM, SEXO, ENTIDAD_NAC, ENTIDAD_RES, MUNICIPIO_RES, TIPO_PACIENTE, FECHA_INGRESO, FECHA_SINTOMAS, FECHA_DEF, INTUBADO, NEUMONIA, EDAD, NACIONALIDAD, EMBARAZO, HABLA_LENGUA_INDIG, DIABETES, EPOC, ASMA, INMUSUPR, HIPERTENSION, OTRA_COM, CARDIOVASCULAR, OBESIDAD, RENAL_CRONICA, TABAQUISMO, OTRO_CASO, RESULTADO, MIGRANTE, PAIS_NACIONALIDAD, PAIS_ORIGEN, UCI]
Index: []

[0 rows x 35 columns]

In [61]:
len(df[pd.isna(df['UCI'])])

0

In [71]:
df['Casos acumulados'] = sum(df['RESULTADO'] != 1)

In [68]:
df['Casos acumulados'].head()

0    0
1    0
2    0
3    0
4    0
Name: Casos acumulados, dtype: int64

In [73]:
del(df['Casos acumulados'])

In [74]:
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [77]:
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [83]:
df.groupby(by = 'ID_REGISTRO')['TABAQUISMO'].describe()

             count  mean  std  min  25%  50%  75%  max
ID_REGISTRO
000316         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
000776         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
001e8b         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
002245         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
00237e         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
...            ...   ...  ...  ...  ...  ...  ...  ...
1e6804         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
1e6e4c         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
1e747c         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
1e78bc         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0
1e7f8d         1.0   2.0  NaN  2.0  2.0  2.0  2.0  2.0

[1000 rows x 8 columns]

In [85]:
df.groupby(by = 'ID_REGISTRO')['TABAQUISMO','OBESIDAD'].count()

/home/enrique/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

             TABAQUISMO  OBESIDAD
ID_REGISTRO
000316                1         1
000776                1         1
001e8b                1         1
002245                1         1
00237e                1         1
...                 ...       ...
1e6804                1         1
1e6e4c                1         1
1e747c                1         1
1e78bc                1         1
1e7f8d                1         1

[1000 rows x 2 columns]

In [88]:
df.groupby(by = 'ID_REGISTRO')['MUNICIPIO_RES'].max() - df.groupby(by = 'MUNICIPIO_RES')['UCI'].min()

000316   NaN
000776   NaN
001e8b   NaN
002245   NaN
00237e   NaN
          ..
174      NaN
175      NaN
189      NaN
193      NaN
197      NaN
Length: 1094, dtype: float64

In [90]:
dfnew = df[df.ENTIDAD_UM.isin(['25','27'])]

In [91]:
dfnew.groupby(by = ['ID_REGISTRO','ENTIDAD_UM'])['TABAQUISMO'].max()

ID_REGISTRO  ENTIDAD_UM
002245       27            2
004228       25            1
004912       27            2
006e42       27            2
008b81       27            2
                          ..
1e124f       27            2
1e142d       27            2
1e2f27       25            2
1e6804       27            2
1e6e4c       25            2
Name: TABAQUISMO, Length: 183, dtype: int64

In [92]:
mygroupby = dfnew.groupby(by = ['ID_REGISTRO','ENTIDAD_UM'])['TABAQUISMO']

In [95]:
mygroupby.count()

ID_REGISTRO  ENTIDAD_UM
002245       27            1
004228       25            1
004912       27            1
006e42       27            1
008b81       27            1
                          ..
1e124f       27            1
1e142d       27            1
1e2f27       25            1
1e6804       27            1
1e6e4c       25            1
Name: TABAQUISMO, Length: 183, dtype: int64

In [100]:
# Para eliminar filas repetidas

dfduplicate = df.append(df)

In [97]:
dfduplicate = dfduplicate.sample(frac=1)

In [98]:
dfclean = dfduplicate.drop_duplicates()

In [99]:
len(dfclean) == len(df)

True

In [101]:
dfclean.drop_duplicates(subset = 'SECTOR')

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
635,2020-07-30,144d47,2,4,9,2,15,9,13,1,...,2,2,2,1,99,1,99,México,99,97
769,2020-07-30,03a8ac,2,3,27,1,27,27,4,1,...,2,2,2,2,1,1,99,México,99,97
935,2020-07-30,007644,2,1,5,2,5,5,35,1,...,2,2,2,2,2,1,99,México,99,97

In [102]:
# Para datos faltantes

df.dropna()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-07-30,051cf3,2,4,9,1,9,9,5,1,...,2,1,2,2,99,1,99,México,99,97
996,2020-07-30,15afc2,2,4,21,2,21,21,114,1,...,2,2,2,2,99,1,99,México,99,97
997,2020-07-30,0734ea,2,4,15,1,15,15,121,1,...,2,1,2,2,99,1,99,México,99,97
998,2020-07-30,103b61,2,4,15,1,9,15,25,1,...,2,1,2,2,99,1,99,México,99,97
999,2020-07-30,0a1951,2,4,23,2,23,23,5,2,...,2,2,2,2,99,1,99,México,99,2

In [104]:
df.dropna(thresh=len(df.columns)-2)   # para que como maximo haya 2 columnas faltantes

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-07-30,051cf3,2,4,9,1,9,9,5,1,...,2,1,2,2,99,1,99,México,99,97
996,2020-07-30,15afc2,2,4,21,2,21,21,114,1,...,2,2,2,2,99,1,99,México,99,97
997,2020-07-30,0734ea,2,4,15,1,15,15,121,1,...,2,1,2,2,99,1,99,México,99,97
998,2020-07-30,103b61,2,4,15,1,9,15,25,1,...,2,1,2,2,99,1,99,México,99,97
999,2020-07-30,0a1951,2,4,23,2,23,23,5,2,...,2,2,2,2,99,1,99,México,99,2